mongo-url = "mongodb://apptestuser:LKJSDL%40Fjrpw%404sjfqoAFsq23rr@10.20.41.254:27017/?replicaSet=edurs0"
elasticsearch-urls = ["http://10.20.41.254:9200"]

gzip = true

#elasticsearch-max-conns = 4
elasticsearch-max-seconds = 5
elasticsearch-retry = true

namespace-regex = '^digital-education\..*'

# write stats to log file or console
stats = true
# index-stats = false # whether to write stats in ES

# on every start reindex every college docs
direct-read-namespaces = ["digital-education.institute", "digital-education.exam"]
exit-after-direct-reads = true

# embedded server to host stats and debug info
#enable-http-server = true
#http-server-addr = ":8081"

#verbose = true
resume = true

[[mapping]]  #index mapping
namespace = "digital-education.institute"
index = "education_search_institute_v1"

[[mapping]]
namespace = "digital-education.exam"
index = "education_search_exam_v1"
type = "education"

# to parse below env variables run monstache with "-tpl" flag
[[script]]
path = '{{index . "HOME"}}/monstache/transform.js'

[[script]]
namespace = "digital-education.exam"
path = '{{index . "HOME"}}/monstache/transformExam.js'

[logs]
info = '{{index . "HOME"}}/monstache/logs/info.log'
warn = '{{index . "HOME"}}/monstache/logs/warn.log'
error = '{{index . "HOME"}}/monstache/logs/error.log'
trace = '{{index . "HOME"}}/monstache/logs/trace.log'
stats = '{{index . "HOME"}}/monstache/logs/stats.log'
