#Staging
#mongo-url = "mongodb://apptestuser:LKJSDL%40Fjrpw%404sjfqoAFsq23rr@10.20.41.254:27017/?replicaSet=edurs0"
#elasticsearch-urls = ["http://10.20.41.254:9200"]

#Prod
mongo-url = "mongodb://app_education:UJQ#%401w%402cD@10.4.33.152:27017/?replicaSet=rs_0"
elasticsearch-urls = ["http://internal-education-es-alb-143014650.ap-south-1.elb.amazonaws.com:9200"]

gzip = true

#elasticsearch-max-seconds = 5
#elasticsearch-max-bytes = 83886080

namespace-regex = 'digital_education.institute'

# write stats to log file or console
stats = true
# index-stats = false # whether to write stats in ES

# embedded server to host stats and debug info
#enable-http-server = true
#http-server-addr = ":8081"

verbose = false
resume = true # data is kept in mongodb to resume

# on every start reindex every institute docs
#direct-read-namespaces = ["digital_education.institute"]
#exit-after-direct-reads = true

#workers = ["A", "B", "C", "D"]

#[gtm-settings]
#channel-size = 2048
#buffer-size = 128
#buffer-duration = "1000ms"


[[mapping]]  #index mapping
namespace = "digital_education.institute"
index = "education_search_institute_v4"
type = "education"


#to parse below env variables run monstache with "-tpl" flag
[[script]]
namespace = "digital_education.institute"
path = '/var/www/monstache/transform.js'

[logs]
info =  '/var/www/monstache/logs/institute/info.log'
warn =  '/var/www/monstache/logs/institute/warn.log'
error = '/var/www/monstache/logs/institute/error.log'
trace = '/var/www/monstache/logs/institute/trace.log'
stats = '/var/www/monstache/logs/institute/stats.log'
